[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "fenitop"
version = "0.1.0"
description = "FEniCSx-based topology optimization"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
  "numpy",
  "scipy",
  "pyvista",
  "psutil",
  "ipyparallel",
  "meshio",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["fenitop*"]
